### ISSUE TITLE
dns issues (google's DNS phone home)

### ISSUE THREAD

**Issue by Thijzer** [mauimauer/cheapcast#34]
I just tried your new service, after a proper setup at first it didn't work, I started hunting for the solution and found that the chromecast uses dns 8.8.8.8 and 8.8.4.4 hardcoded inside the service to phone home. Without it, it simple doesn't work. 
So my issue was that apparently my router was redirecting these google dns requests to it's own dns servers.

This most likely the reason why many people have connection issues, simple because their router DNS is setup differently.

https://support.google.com/chromecast/answer/3228330?hl=en

Now there are workarounds on the router side but these are the bad ones. 
My question is : can this issue be altered/fixed in the source code so it would work with any dns server?

thanks,

Thijs

**Comment by mauimauer** [comment]
Hi Thijs,

I can guarantee that it works fine with other DNS servers. Heck, I'm not even using the Google DNS but the one offered by my ISP. I guess they mention it on their support page in order to help people with broken DNS setups (which can In fact disrupt communication between ChromeCast and ChromeCast Apps)

The discovery itself works using SSDP/DIAL, which is a Protocol based on UDP Multicast packets, this should be completely agnostic to DNS

The actual ChromeCast Apps (ie. the HTML5 based Apps that run "on" the ChromeCast) are fetched from remote Servers (like Google in the case of Google Music, Google Movies, Tab Casting and YouTube). This requires a proper DNS setup since it needs to resolve the remote Domains.
