### ISSUE TITLE
Cheapcast not playing Youtube movies (Gray screen)

### ISSUE THREAD

**Issue by ghost** [mauimauer/cheapcast#39]
Running a Tronsmart T428 with the Hybrid Firmware ROM. I've tried the offical, thinless, nexus (a like) roms but all seem to fail to play Youtube movies over chromecast.

I've downloaded the newest Youtube app from the store and disabled the older one (since the gapps werent completly up to date), but still no luck :(

Can anyone help me?

**Comment by jimmed** [comment]
I'm also experiencing this issue, running on an OUYA (rooted w/ Play Store). The metadata for the video is shown on-screen, but instead of the video playing back there is a grey box with a video icon on it. I'm happy to supply any information required from the device to help solve this - I would love it to work!

FWIW, Play Music works absolutely flawlessly!

**Comment by Dunkerton21** [comment]
Same here using an MK808b. Version 0.3.7 of Cheapcast worked fine, but since 0.3.8 I get the exact same problem as listed above.

**Comment by shellstrom** [comment]
I'm running cm 10.1.3 on a Nexus Q, same issue. If I have understood the root cause for this, it is because something changed on Google's side that makes Cheapcast incompatible. The solution then would be to adapt Cheapcast to the change and publish a new update. Now, the tricky bit is to determine what changed andf whether Cheapcast can be modified to get the support back. And after that its a question of wehether a developer has time to do all of the necessary modifications.

**Comment by mauimauer** [comment]
An update is already on the way. Stay tuned ;)

**Comment by ghost** [comment]
Just wondering, how long does it take before the new version is online?

**Comment by jimmed** [comment]
This now works on version 0.41 on my Ouya btw :+1:

**Comment by ghost** [comment]
Thanks for replying Jimmed, I now can confirm it is also works on my Tronsmart T428.
